// GENERATED by tools/gen_layouts.py from schema/layouts.json - DO NOT EDIT.
// Change the schema, then re-run `python tools/gen_layouts.py`.
//
// Field layouts of the records the agents read. scripts/_lib.js's readRecord()
// walks these tables, so this is the only place in scripts/ that knows an
// offset - the agents themselves never spell one out.

/**
 * One readable field of a record: where it sits (relative to the object
 * pointer), and a type name that scripts/_lib.js's FIELD_READERS knows.
 * @typedef {{name: string, offset: number, type: string}} FieldSpec
 */

/** System.String: int32 length at lengthOffset, UTF-16LE chars from charsOffset. */
export const Il2CppStringLayout = { lengthOffset: 0x08, charsOffset: 0x0c };

/**
 * One entry of ExampleNamespace.DeviceQualityAllowList, as read from a hooked `...$$unpack` call.
 *
 * @typedef {Object} DeviceQualityRecord
 * @property {number} id - numeric record id [+0x08, uint32]
 * @property {number} enabled - HD render quality on/off flag (observed as 0 or 1) [+0x18, int8]
 * @property {string|null} name - device name/identifier [+0x20, System.String*]; null on a null
 *   pointer, or a `<...>` placeholder string on an unexpected length / read error - see
 *   readIl2CppString in _lib.js
 */

/** @type {FieldSpec[]} */
export const DeviceQualityRecordLayout = [
    { name: "id", offset: 0x08, type: "u32" },
    { name: "enabled", offset: 0x18, type: "s8" },
    { name: "name", offset: 0x20, type: "string" },
];

/**
 * One entry of ExampleNamespace.DeviceRecommendConfig, as read from a hooked `...$$unpack` call.
 *
 * @typedef {Object} RecommendConfigRecord
 * @property {number} id - numeric record id [+0x08, uint32]
 * @property {number} type - record type discriminator [+0x0c, uint32]
 * @property {number} paramMin1 - [+0x18, int32]
 * @property {number} paramMax1 - [+0x1c, int32]
 * @property {number} paramMin2 - [+0x20, int32]
 * @property {number} paramMax2 - [+0x24, int32]
 * @property {number} paramMin3 - [+0x28, int32]
 * @property {number} paramMax3 - [+0x2c, int32]
 * @property {number} deviceLevel - [+0x30, uint32]
 * @property {number} supportsFPS60 - observed as a 0/1 flag [+0x34, uint32]
 * @property {number} supportsParticleHD - observed as a 0/1 flag [+0x38, uint32]
 * @property {number} recommendGraphicMode - [+0x3c, uint32]
 * @property {number} renderQualityPerfMode - [+0x40, uint32]
 * @property {number} particleQualityPerfMode - [+0x44, uint32]
 * @property {number} resolutionPerfMode - [+0x48, uint32]
 * @property {number} fpsPerfMode - [+0x4c, uint32]
 * @property {number} renderQualityGraphicMode - [+0x50, uint32]
 * @property {number} particleQualityGraphicMode - [+0x54, uint32]
 * @property {number} resolutionGraphicMode - [+0x58, uint32]
 * @property {number} fpsGraphicMode - [+0x5c, uint32]
 * @property {string|null} szConfig - graphics preset name [+0x60, System.String*]; null on a null
 *   pointer, or a `<...>` placeholder string on an unexpected length / read error - see
 *   readIl2CppString in _lib.js
 */

/** @type {FieldSpec[]} */
export const RecommendConfigRecordLayout = [
    { name: "id", offset: 0x08, type: "u32" },
    { name: "type", offset: 0x0c, type: "u32" },
    { name: "paramMin1", offset: 0x18, type: "s32" },
    { name: "paramMax1", offset: 0x1c, type: "s32" },
    { name: "paramMin2", offset: 0x20, type: "s32" },
    { name: "paramMax2", offset: 0x24, type: "s32" },
    { name: "paramMin3", offset: 0x28, type: "s32" },
    { name: "paramMax3", offset: 0x2c, type: "s32" },
    { name: "deviceLevel", offset: 0x30, type: "u32" },
    { name: "supportsFPS60", offset: 0x34, type: "u32" },
    { name: "supportsParticleHD", offset: 0x38, type: "u32" },
    { name: "recommendGraphicMode", offset: 0x3c, type: "u32" },
    { name: "renderQualityPerfMode", offset: 0x40, type: "u32" },
    { name: "particleQualityPerfMode", offset: 0x44, type: "u32" },
    { name: "resolutionPerfMode", offset: 0x48, type: "u32" },
    { name: "fpsPerfMode", offset: 0x4c, type: "u32" },
    { name: "renderQualityGraphicMode", offset: 0x50, type: "u32" },
    { name: "particleQualityGraphicMode", offset: 0x54, type: "u32" },
    { name: "resolutionGraphicMode", offset: 0x58, type: "u32" },
    { name: "fpsGraphicMode", offset: 0x5c, type: "u32" },
    { name: "szConfig", offset: 0x60, type: "string" },
];

/**
 * The fields of RecommendConfigRecord that dump_selection_logic.js watches live. Both functions it
 * hooks return a pointer to a full DeviceRecommendConfig record; only these fields are read.
 *
 * @typedef {Pick<RecommendConfigRecord, "id"|"type"|"deviceLevel"|"fpsGraphicMode"|"szConfig">} SelectionResult
 */

/** Pass to readRecord(ptr, RecommendConfigRecordLayout, SelectionResultFields). */
export const SelectionResultFields = ["id", "type", "deviceLevel", "fpsGraphicMode", "szConfig"];
