"""
gen_layouts.py

schema/layouts.json is the ONE place that says where a record's fields live
(offset), how each is read (type) and what it means. Nothing else in the
repo restates an offset by hand - these are generated from it:

    scripts/_layouts.js     layout tables the Frida agents read with, plus the
                            JSDoc typedefs for the records they produce
    tools/records.py        the TypedDicts the Python drivers annotate with
    docs/MEMORY_LAYOUT.md   the offset listings between the
                            `<!-- BEGIN GENERATED: ... -->` markers

Usage (from the repo root):

    python tools/gen_layouts.py           # rewrite the generated files
    python tools/gen_layouts.py --check   # exit 1 if any of them is stale

tests/test_layouts.py runs the same staleness check, and also checks that the
JS reader really decodes every type the way the schema says (see there), so
neither a hand edit of a generated file nor a change to a reader can drift
from the schema unnoticed.
"""
import argparse
import json
import keyword
import re
import sys
import textwrap
from collections import namedtuple
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMA_PATH = REPO_ROOT / "schema" / "layouts.json"
LAYOUTS_JS_PATH = REPO_ROOT / "scripts" / "_layouts.js"
RECORDS_PY_PATH = REPO_ROOT / "tools" / "records.py"
MEMORY_LAYOUT_MD_PATH = REPO_ROOT / "docs" / "MEMORY_LAYOUT.md"

# Same cap check_placeholders.py applies to struct-field tables in JS
# (tests/test_layouts.py asserts the two stay equal): anything bigger than a
# plausible field offset looks like a code address and doesn't belong here.
MAX_FIELD_OFFSET = 0x1000

FieldType = namedtuple("FieldType", "size py js label js_note")

# The vocabulary of `type` in the schema. Adding a type means adding it here
# AND to FIELD_READERS in scripts/_lib.js - tests/test_layouts.py fails if
# the two sets differ, and decodes every type in both languages to compare.
TYPES = {
    "u32": FieldType(4, "int", "number", "uint32", ""),
    "s32": FieldType(4, "int", "number", "int32", ""),
    "s8": FieldType(1, "int", "number", "int8", ""),
    "string": FieldType(
        8, "Optional[str]", "string|null", "System.String*",
        "null on a null pointer, or a `<...>` placeholder string on an "
        "unexpected length / read error - see readIl2CppString in _lib.js"),
}

_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_GENERATED_LINES = ("GENERATED by tools/gen_layouts.py from schema/layouts.json - DO NOT EDIT.",
                    "Change the schema, then re-run `python tools/gen_layouts.py`.")


class SchemaError(ValueError):
    pass


# ---------------------------------------------------------------------------
# loading + validation
# ---------------------------------------------------------------------------

def _offset(value, where):
    if isinstance(value, str) and re.fullmatch(r"0[xX][0-9a-fA-F]+", value):
        value = int(value, 16)
    if not isinstance(value, int) or isinstance(value, bool):
        raise SchemaError(f"{where}: offset must be a 0x-prefixed hex string, got {value!r}")
    if not 0 <= value <= MAX_FIELD_OFFSET:
        raise SchemaError(f"{where}: offset {value:#x} is outside 0..{MAX_FIELD_OFFSET:#x} - "
                          "only small struct-field offsets belong here, not code addresses")
    return value


def _ident(name, where):
    if not isinstance(name, str) or not _IDENT_RE.match(name) or keyword.iskeyword(name):
        raise SchemaError(f"{where}: {name!r} is not a usable identifier")
    return name


def _require(cond, msg):
    if not cond:
        raise SchemaError(msg)


def validate(raw):
    """Check `raw` (the parsed schema) and return a normalised copy: offsets
    as ints, fields in offset order, subsets expanded to their fields."""
    header = raw.get("headerSize")
    _require(isinstance(header, int) and header > 0, "headerSize must be a positive integer")

    s_raw = raw.get("il2cppString") or {}
    length_at = _offset(s_raw.get("lengthOffset"), "il2cppString.lengthOffset")
    chars_at = _offset(s_raw.get("charsOffset"), "il2cppString.charsOffset")
    _require(length_at >= header, "il2cppString.lengthOffset overlaps the object header")
    _require(chars_at == length_at + TYPES["s32"].size,
             "il2cppString.charsOffset must start right after the int32 length")

    records = {}
    _require(raw.get("records"), "no records defined")
    for rname, r in raw["records"].items():
        rwhere = f"records.{_ident(rname, 'record name')}"
        fields, seen = [], set()
        for f in r.get("fields", []):
            fname = _ident(f.get("name"), f"{rwhere}.fields[].name")
            where = f"{rwhere}.{fname}"
            _require(fname not in seen, f"{where}: duplicate field name")
            seen.add(fname)
            _require(f.get("type") in TYPES, f"{where}: unknown type {f.get('type')!r} "
                                             f"(known: {', '.join(TYPES)})")
            off = _offset(f.get("offset"), where)
            size = TYPES[f["type"]].size
            _require(off % size == 0, f"{where}: offset {off:#x} is not naturally aligned "
                                      f"for a {size}-byte {f['type']}")
            fields.append({"name": fname, "offset": off, "type": f["type"], "doc": f.get("doc", "")})
        _require(fields, f"{rwhere}: no fields")
        _require([f["offset"] for f in fields] == sorted(f["offset"] for f in fields),
                 f"{rwhere}: fields must be listed in ascending offset order")

        unread = []
        for u in r.get("unread", []):
            uname = _ident(u.get("name"), f"{rwhere}.unread[].name")
            where = f"{rwhere}.{uname}"
            _require(uname not in seen, f"{where}: duplicate field name")
            seen.add(uname)
            size = u.get("size")
            _require(isinstance(size, int) and size > 0, f"{where}: size must be a positive integer")
            _require(u.get("doc"), f"{where}: an unread region needs a doc line")
            unread.append({"name": uname, "offset": _offset(u.get("offset"), where),
                           "size": size, "doc": u["doc"]})

        end = header
        for e in sorted(fields + unread, key=lambda e: e["offset"]):
            size = e["size"] if "size" in e else TYPES[e["type"]].size
            _require(e["offset"] >= end, f"{rwhere}.{e['name']}: overlaps the previous field "
                                         f"or the {header}-byte object header")
            end = e["offset"] + size

        agent = r.get("agent")
        _require(agent is None or (isinstance(agent, str) and agent.endswith(".js")),
                 f"{rwhere}: agent must be a .js file name")
        records[rname] = {"description": r.get("description", ""), "agent": agent,
                          "fields": fields, "unread": unread}

    subsets = {}
    for sname, s in raw.get("subsets", {}).items():
        swhere = f"subsets.{_ident(sname, 'subset name')}"
        _require(sname not in records, f"{swhere}: clashes with a record name")
        _require(s.get("of") in records, f"{swhere}: unknown record {s.get('of')!r}")
        names = s.get("fields") or []
        _require(names and len(set(names)) == len(names), f"{swhere}: fields must be non-empty and unique")
        parent = {f["name"]: f for f in records[s["of"]]["fields"]}
        missing = [n for n in names if n not in parent]
        _require(not missing, f"{swhere}: not readable fields of {s['of']}: {', '.join(missing)}")
        subsets[sname] = {"of": s["of"], "description": s.get("description", ""),
                          "agent": s.get("agent"),
                          "fields": [f for f in records[s["of"]]["fields"] if f["name"] in names]}

    return {"header_size": header,
            "string": {"length_offset": length_at, "chars_offset": chars_at},
            "records": records, "subsets": subsets}


def load_schema(path=SCHEMA_PATH):
    return validate(json.loads(Path(path).read_text(encoding="utf-8")))


# ---------------------------------------------------------------------------
# renderers
# ---------------------------------------------------------------------------

def _hex(v):
    return f"0x{v:02x}"


def _jsdoc(text, first=" * ", rest=" * "):
    return textwrap.wrap(text, width=100, initial_indent=first, subsequent_indent=rest,
                         break_long_words=False, break_on_hyphens=False)


def _property_doc(f):
    t = TYPES[f["type"]]
    text = (f["doc"] + " " if f["doc"] else "") + f"[+{_hex(f['offset'])}, {t.label}]"
    if t.js_note:
        text += f"; {t.js_note}"
    return f"@property {{{t.js}}} {f['name']} - {text}"


def render_layouts_js(schema):
    out = [f"// {line}" for line in _GENERATED_LINES] + ["//",
           "// Field layouts of the records the agents read. scripts/_lib.js's readRecord()",
           "// walks these tables, so this is the only place in scripts/ that knows an",
           "// offset - the agents themselves never spell one out.", "",
           "/**",
           " * One readable field of a record: where it sits (relative to the object",
           " * pointer), and a type name that scripts/_lib.js's FIELD_READERS knows.",
           " * @typedef {{name: string, offset: number, type: string}} FieldSpec",
           " */", ""]

    s = schema["string"]
    out += ["/** System.String: int32 length at lengthOffset, UTF-16LE chars from charsOffset. */",
            f"export const Il2CppStringLayout = {{ lengthOffset: {_hex(s['length_offset'])}, "
            f"charsOffset: {_hex(s['chars_offset'])} }};", ""]

    for rname, r in schema["records"].items():
        out += ["/**"] + _jsdoc(r["description"]) + [" *", f" * @typedef {{Object}} {rname}"]
        for f in r["fields"]:
            out += _jsdoc(_property_doc(f), rest=" *   ")
        out += [" */", ""]
        out += [f"/** @type {{FieldSpec[]}} */", f"export const {rname}Layout = ["]
        out += [f'    {{ name: "{f["name"]}", offset: {_hex(f["offset"])}, type: "{f["type"]}" }},'
                for f in r["fields"]]
        out += ["];", ""]

    for sname, s in schema["subsets"].items():
        names = [f["name"] for f in s["fields"]]
        union = "|".join(f'"{n}"' for n in names)
        out += ["/**"] + _jsdoc(s["description"]) + [
            " *", f" * @typedef {{Pick<{s['of']}, {union}>}} {sname}", " */", "",
            f"/** Pass to readRecord(ptr, {s['of']}Layout, {sname}Fields). */",
            "export const " + f"{sname}Fields = [" + ", ".join(f'"{n}"' for n in names) + "];", ""]
    return "\n".join(out).rstrip("\n") + "\n"


def render_records_py(schema):
    out = ['"""', "records.py", "", *_GENERATED_LINES, "",
           "TypedDict schemas for the JSON records the Frida agents in scripts/ send back over",
           "rpc.exports (see run_hd_quality_dump.py's `get_records()` call). They are derived",
           "from the same schema/layouts.json the agents read their memory with, so the field",
           "names and Python types here cannot disagree with what the agents produce; the",
           "JS-side decoding of each type is checked against that schema by",
           "tests/test_layouts.py.",
           "",
           "Still just annotations: nothing runs mypy/pyright over them, and",
           "rpc.exports.get_records() itself returns a plain `list[dict]` at runtime.",
           '"""',
           "from typing import Optional, TypedDict"]

    def cls(name, doc_lines, fields):
        lines = ["", "", f"class {name}(TypedDict):", '    """' + doc_lines[0]]
        lines += [("    " + l).rstrip() for l in doc_lines[1:]]
        lines += ['    """']
        lines += [f"    {f['name']}: {TYPES[f['type']].py}" for f in fields]
        return lines

    for rname, r in schema["records"].items():
        docs = textwrap.wrap(r["description"], width=72)
        if r["agent"]:
            docs += ["", f"Read by scripts/{r['agent']}."]
        out += cls(rname, docs, r["fields"])
    for sname, s in schema["subsets"].items():
        docs = textwrap.wrap(s["description"], width=72)
        docs += ["", f"Subset of {s['of']}" + (f", read by scripts/{s['agent']}." if s["agent"] else ".")]
        out += cls(sname, docs, s["fields"])
    return "\n".join(out).rstrip("\n") + "\n"


def _layout_block(schema, record):
    """The offset listing for one record, as a fenced block plus notes."""
    header = schema["header_size"]
    entries = [dict(f, kind="field", size=TYPES[f["type"]].size) for f in record["fields"]]
    entries += [dict(u, kind="unread") for u in record["unread"]]
    entries.sort(key=lambda e: e["offset"])
    width = max(len(e["name"]) for e in entries) + 2

    rows = [f"+{_hex(0)}  {'klass':<{width}}object header ({header} bytes)"]
    cursor = header
    for e in entries:
        if e["offset"] > cursor:
            rows.append(f"+{_hex(cursor)}  (padding, {e['offset'] - cursor} bytes)")
        if e["kind"] == "field":
            t = TYPES[e["type"]]
            row = f"+{_hex(e['offset'])}  {e['name']:<{width}}{t.label:<16}{e['doc']}"
        else:
            row = f"+{_hex(e['offset'])}  {e['name']:<{width}}(not read; {e['size']} bytes)"
        rows.append(row.rstrip())
        cursor = e["offset"] + e["size"]

    out = ["```text"] + rows + ["```"]
    for u in record["unread"]:
        out += ["", f"`{u['name']}` (`+{_hex(u['offset'])}..{_hex(u['offset'] + u['size'] - 1)}`): {u['doc']}"]
    return "\n".join(out)


def render_doc_blocks(schema):
    s = schema["string"]
    blocks = {"il2cpp-string": "\n".join([
        "```text",
        f"+{_hex(0)}  klass    ({schema['header_size']} bytes, object header)",
        f"+{_hex(s['length_offset'])}  length   (int32, NOT padded to 8 bytes)",
        f"+{_hex(s['chars_offset'])}  UTF-16LE chars, starting immediately after length, no gap",
        "```"])}
    for rname, r in schema["records"].items():
        blocks[rname] = _layout_block(schema, r)
    return blocks


_BLOCK_RE = re.compile(r"(<!-- BEGIN GENERATED: (?P<key>[\w-]+)[^>]*-->\n)(.*?)(<!-- END GENERATED: (?P=key) -->)",
                       re.DOTALL)


def apply_doc_blocks(text, blocks):
    """Replace the body of every `<!-- BEGIN GENERATED: key --> ... <!-- END
    GENERATED: key -->` region in `text` with blocks[key]."""
    found = set()

    def sub(m):
        key = m.group("key")
        if key not in blocks:
            raise SchemaError(f"docs/MEMORY_LAYOUT.md has a GENERATED region {key!r} the schema doesn't define")
        found.add(key)
        return m.group(1) + blocks[key] + "\n" + m.group(4)

    new = _BLOCK_RE.sub(sub, text)
    missing = sorted(set(blocks) - found)
    if missing:
        raise SchemaError("docs/MEMORY_LAYOUT.md is missing GENERATED region(s): " + ", ".join(missing))
    return new


def strip_generated_regions(text):
    """`text` with every generated region emptied - what's left is hand-written."""
    return _BLOCK_RE.sub(lambda m: m.group(1) + m.group(4), text)


def expected_outputs(schema, memory_layout_text):
    """{path: the content that file should have right now}."""
    return {
        LAYOUTS_JS_PATH: render_layouts_js(schema),
        RECORDS_PY_PATH: render_records_py(schema),
        MEMORY_LAYOUT_MD_PATH: apply_doc_blocks(memory_layout_text, render_doc_blocks(schema)),
    }


def main(argv=None):
    ap = argparse.ArgumentParser(description="Generate the files derived from schema/layouts.json.")
    ap.add_argument("--check", action="store_true", help="don't write; exit 1 if anything is stale")
    args = ap.parse_args(argv)

    try:
        schema = load_schema()
        wanted = expected_outputs(schema, MEMORY_LAYOUT_MD_PATH.read_text(encoding="utf-8"))
    except (SchemaError, OSError, json.JSONDecodeError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 2

    stale = [p for p, text in wanted.items()
             if not p.exists() or p.read_text(encoding="utf-8") != text]
    if args.check:
        for p in stale:
            print(f"stale: {p.relative_to(REPO_ROOT)} - run `python tools/gen_layouts.py`", file=sys.stderr)
        return 1 if stale else 0

    for p in stale:
        # open() rather than Path.write_text(newline=...), which needs Python 3.10+.
        with open(p, "w", encoding="utf-8", newline="\n") as f:
            f.write(wanted[p])
        print(f"wrote {p.relative_to(REPO_ROOT)}")
    if not stale:
        print("up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
