"""
records.py

GENERATED by tools/gen_layouts.py from schema/layouts.json - DO NOT EDIT.
Change the schema, then re-run `python tools/gen_layouts.py`.

TypedDict schemas for the JSON records the Frida agents in scripts/ send back over
rpc.exports (see run_hd_quality_dump.py's `get_records()` call). They are derived
from the same schema/layouts.json the agents read their memory with, so the field
names and Python types here cannot disagree with what the agents produce; the
JS-side decoding of each type is checked against that schema by
tests/test_layouts.py.

Still just annotations: nothing runs mypy/pyright over them, and
rpc.exports.get_records() itself returns a plain `list[dict]` at runtime.
"""
from typing import Optional, TypedDict


class DeviceQualityRecord(TypedDict):
    """One entry of ExampleNamespace.DeviceQualityAllowList, as read from a
    hooked `...$$unpack` call.

    Read by scripts/dump_hd_quality_list.js.
    """
    id: int
    enabled: int
    name: Optional[str]


class RecommendConfigRecord(TypedDict):
    """One entry of ExampleNamespace.DeviceRecommendConfig, as read from a
    hooked `...$$unpack` call.

    Read by scripts/dump_recommend_config.js.
    """
    id: int
    type: int
    paramMin1: int
    paramMax1: int
    paramMin2: int
    paramMax2: int
    paramMin3: int
    paramMax3: int
    deviceLevel: int
    supportsFPS60: int
    supportsParticleHD: int
    recommendGraphicMode: int
    renderQualityPerfMode: int
    particleQualityPerfMode: int
    resolutionPerfMode: int
    fpsPerfMode: int
    renderQualityGraphicMode: int
    particleQualityGraphicMode: int
    resolutionGraphicMode: int
    fpsGraphicMode: int
    szConfig: Optional[str]


class SelectionResult(TypedDict):
    """The fields of RecommendConfigRecord that dump_selection_logic.js watches
    live. Both functions it hooks return a pointer to a full
    DeviceRecommendConfig record; only these fields are read.

    Subset of RecommendConfigRecord, read by scripts/dump_selection_logic.js.
    """
    id: int
    type: int
    deviceLevel: int
    fpsGraphicMode: int
    szConfig: Optional[str]
